# We ideally want something like: https://github.com/j178/prek/issues/1869
---
default_language_version:
  node: system

repos:
  - repo: local
    hooks:
      - id: cargo-doc
        name: cargo-doc
        language: system
        env:
          K8S_OPENAPI_ENABLED_VERSION: "1.36"
        entry: cargo doc --no-deps --document-private-items --package stackable-versioned
        stages: [pre-commit, pre-merge-commit]
        pass_filenames: false
        files: \.rs$|Cargo\.(toml|lock)

      - id: cargo-doc-no-default-features
        name: cargo-doc-no-default-features
        language: system
        env:
          K8S_OPENAPI_ENABLED_VERSION: "1.36"
        entry: cargo doc --no-deps --no-default-features --document-private-items --package stackable-versioned
        stages: [pre-commit, pre-merge-commit]
        pass_filenames: false
        files: \.rs$|Cargo\.(toml|lock)

      - id: cargo-doc-all-features
        name: cargo-doc-all-features
        language: system
        env:
          K8S_OPENAPI_ENABLED_VERSION: "1.36"
        entry: cargo doc --no-deps --all-features --document-private-items --package stackable-versioned
        stages: [pre-commit, pre-merge-commit]
        pass_filenames: false
        files: \.rs$|Cargo\.(toml|lock)

      - id: cargo-test-no-default-features
        name: cargo-test-no-default-features
        language: system
        entry: cargo test --no-default-features --package stackable-versioned
        stages: [pre-commit, pre-merge-commit]
        pass_filenames: false
        files: .*\.rs$|Cargo\.toml

      - id: cargo-test-all-features
        name: cargo-test-all-default-features
        language: system
        entry: cargo test --all-features --package stackable-versioned
        stages: [pre-commit, pre-merge-commit]
        pass_filenames: false
        files: .*\.rs$|Cargo\.toml
