version: 2
updates:
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
    labels:
      - "type/dependencies"
    reviewers:
      - "stackabletech/developers"

  - package-ecosystem: "cargo"
    directory: "/"
    schedule:
      interval: "weekly"
    labels:
      - "type/dependencies"
    reviewers:
      - "stackabletech/rust-developers"
