version: 2
updates:
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "daily"

  - package-ecosystem: "cargo"
    directory: "/"
    schedule:
      interval: "daily"
    ignore:
      # We never want to be notified about a kube-rs update
      # It often contains breaking changes so can't be updated manually anyway
      # and it needs to be updated together with kube-runtime, kube-derive etc.
      - dependency-name: "kube*"
