---
extends: default

rules:
  line-length: disable
  truthy:
    check-keys: false
  comments:
    min-spaces-from-content: 1  # Needed due to https://github.com/adrienverge/yamllint/issues/443
  indentation:
    ignore:
      crates/stackable-operator/crds/*.yaml
