# https://doc.rust-lang.org/nightly/edition-guide/rust-2024/rustfmt-style-edition.html
style_edition = "2024"
imports_granularity = "Crate"
group_imports = "StdExternalCrate"
reorder_impl_items = true
use_field_init_shorthand = true
