use kube::CustomResource;
use schemars::JsonSchema;
use serde::{Deserialize, Serialize};
use stackable_versioned_macros::versioned;

use crate as stackable_versioned;

#[versioned(
    k8s(group = "test.stackable.tech",),
    version(name = "v1alpha1"),
    version(name = "v1alpha2"),
    version(name = "v1beta1"),
    version(name = "v2"),
    version(name = "v3")
)]
#[derive(
    Clone,
    Debug,
    Eq,
    Hash,
    Ord,
    PartialEq,
    PartialOrd,
    CustomResource,
    Deserialize,
    JsonSchema,
    Serialize,
)]
#[serde(rename_all = "camelCase")]
struct PersonSpec {
    username: String,

    // In v1alpha2 first and last name have been added
    #[versioned(added(since = "v1alpha2"))]
    first_name: String,
    #[versioned(added(since = "v1alpha2"))]
    last_name: String,

    // We started out with a enum. As we *need* to provide a default, we have a Unknown variant.
    // Afterwards we figured let's be more flexible and accept any arbitrary String.
    #[versioned(
        added(since = "v2", default = "default_gender"),
        changed(since = "v3", from_type = "Gender")
    )]
    gender: String,
}

fn default_gender() -> Gender {
    Gender::Unknown
}

#[derive(
    Clone, Debug, Eq, Hash, Ord, PartialEq, PartialOrd, Deserialize, JsonSchema, Serialize,
)]
#[serde(rename_all = "PascalCase")]
pub enum Gender {
    Unknown,
    Male,
    Female,
}

impl Into<String> for Gender {
    fn into(self) -> String {
        match self {
            Gender::Unknown => "Unknown".to_string(),
            Gender::Male => "Male".to_string(),
            Gender::Female => "Female".to_string(),
        }
    }
}
impl From<String> for Gender {
    fn from(value: String) -> Self {
        match value.as_str() {
            "Male" => Self::Male,
            "Female" => Self::Female,
            _ => Self::Unknown,
        }
    }
}

/// TEMP, we need to implement downgrades manually
impl From<v1alpha2::PersonSpec> for v1alpha1::PersonSpec {
    fn from(value: v1alpha2::PersonSpec) -> Self {
        Self {
            username: value.username,
        }
    }
}
impl From<v1beta1::PersonSpec> for v1alpha2::PersonSpec {
    fn from(value: v1beta1::PersonSpec) -> Self {
        Self {
            username: value.username,
            first_name: value.first_name,
            last_name: value.last_name,
        }
    }
}
impl From<v2::PersonSpec> for v1beta1::PersonSpec {
    fn from(value: v2::PersonSpec) -> Self {
        Self {
            username: value.username,
            first_name: value.first_name,
            last_name: value.last_name,
        }
    }
}
impl From<v3::PersonSpec> for v2::PersonSpec {
    fn from(value: v3::PersonSpec) -> Self {
        Self {
            username: value.username,
            first_name: value.first_name,
            last_name: value.last_name,
            gender: value.gender.into(),
        }
    }
}
/// END TEMP

#[cfg(test)]
mod tests {
    use super::Person;

    #[test]
    fn parse_simple_example_from_k8s() {
        // this file contains dump of real request generated by kubernetes v1.22
        // Copied from https://github.com/kube-rs/kube/blob/main/kube-core/src/conversion/test_data/simple.json
        let data = include_str!("./test_data/simple_from_k8s.json");
        // check that we can parse this review, and all chain of conversion worls
        let review = serde_json::from_str(data).expect("invalid ConversionReview");
        let request = kube::core::conversion::ConversionRequest::from_review(review)
            .expect("failed to get conversion request from review");
        let response = kube::core::conversion::ConversionResponse::for_request(request);
        let _ = response.into_review();
    }

    #[test]
    fn test_macro() {
        let data = include_str!("./test_data/convert_person_to_v2.json");
        let review: kube::core::conversion::ConversionReview =
            serde_json::from_str(data).expect("invalid ConversionReview");

        let response = Person::convert(review);
        assert_eq!(
            serde_json::to_string(&response).unwrap(),
            "{\"uid\":\"c4e55572-ee1f-4e94-9097-28936985d45f\",\"result\":{\"status\":\"Success\"},\"convertedObjects\":[{\"firstName\":\"\",\"gender\":\"Unknown\",\"lastName\":\"\",\"username\":\"sbernauer\"}]}"
        );
    }
}
