[package]
name = "k8s-version"
version = "0.1.0"
authors.workspace = true
license.workspace = true
edition.workspace = true
repository.workspace = true

[dependencies]
lazy_static.workspace = true
regex.workspace = true
snafu.workspace = true

[dev-dependencies]
rstest.workspace = true
