---
name: "🐛 Bug Report"
description: "If something isn't working as expected 🤔."
labels: ["type/bug"]
body:
  - type: markdown
    attributes:
      value: Thanks for taking the time to file a bug report! Please fill out this form as completely as possible.

  - type: input
    attributes:
      label: Affected version
      description: Which version do you see this bug in?

  - type: textarea
    attributes:
      label: Current and expected behavior
      description: A clear and concise description of what operator-rs is doing and what you would expect.
    validations:
      required: true

  - type: textarea
    attributes:
      label: Possible solution
      description: "If you have suggestions on a fix for the bug."

  - type: textarea
    attributes:
      label: Additional context
      description: "Add any other context about the problem here. Or a screenshot if applicable."

  - type: textarea
    attributes:
      label: Environment
      description: |
        What type of kubernetes cluster you are running aginst (k3s/eks/aks/gke/other) and any other information about your environment?
      placeholder: |
        Examples:
        Output of `kubectl version --short`

  - type: dropdown
    attributes:
      label: Would you like to work on fixing this bug?
      description: |
        **NOTE**: Let us know if you would like to submit a PR for this. We are more than happy to help you through the process.
      options:
        - "yes"
        - "no"
        - "maybe"
