[package]
name = "config-utils"
version = "0.5.0"
authors = ["Stackable GmbH <info@stackable.tech>"]
license = "Apache-2.0"
edition = "2024"
repository = "https://github.com/stackabletech/operator-rs"

[dependencies]
# We try hard to have as less dependencies as possible!
clap.workspace = true
snafu.workspace = true

[dev-dependencies]
rstest.workspace = true
similar-asserts.workspace = true
tempfile.workspace = true
