pub use stackable_operator_derive::Optional;

/// A type that signals it was derived via `stackable_operator_derive::Optional` and that all
/// fields (e.g. of a struct) are optional.
///
/// This is generated by the `stackable_operator_derive::Optional` macro in order to assure
/// type safety.
///
/// This trait does not need to be implemented!
pub trait Optional {}
