[package]
authors = ["Stackable GmbH <info@stackable.de>"]
description = "Stackable Operator Framework"
edition = "2021"
license = "Apache-2.0"
name = "stackable-operator-derive"
version = "0.25.2"
repository = "https://github.com/stackabletech/operator-rs"

[lib]
proc-macro = true

[dependencies]
darling = "0.14.1"
proc-macro2 = "1.0.43"
quote = "1.0.21"
syn = "1.0.99"

[dev-dependencies]
stackable-operator = { path = ".." }
