---
apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: openlineageconnections.openlineage.stackable.tech
spec:
  group: openlineage.stackable.tech
  names:
    categories: []
    kind: OpenLineageConnection
    plural: openlineageconnections
    shortNames: []
    singular: openlineageconnection
  scope: Namespaced
  versions:
  - additionalPrinterColumns: []
    name: v1alpha1
    schema:
      openAPIV3Schema:
        description: A reusable definition of a connection to an OpenLineage backend.
        properties:
          spec:
            description: |-
              OpenLineage connection definition as a resource.
              Learn more about [OpenLineage](https://openlineage.io/).
            properties:
              credentialsSecretName:
                description: |-
                  Name of a Secret containing the API key used to authenticate against the OpenLineage
                  backend. The API key must be stored under the key `apiKey`. The Secret must be located in
                  the same namespace as the workload using this connection. If not specified, no
                  authentication is used.
                nullable: true
                type: string
              host:
                description: 'Host of the OpenLineage backend without any protocol or port. For example: `marquez`.'
                type: string
              port:
                description: 'Port the OpenLineage backend listens on. For example: `5000`.'
                format: uint16
                maximum: 65535.0
                minimum: 0.0
                type: integer
              tls:
                description: Use a TLS connection. If not specified no TLS will be used.
                nullable: true
                properties:
                  verification:
                    description: The verification method used to verify the certificates of the server and/or the client.
                    oneOf:
                    - required:
                      - none
                    - required:
                      - server
                    properties:
                      none:
                        description: Use TLS but don't verify certificates.
                        type: object
                      server:
                        description: Use TLS and a CA certificate to verify the server.
                        properties:
                          caCert:
                            description: CA cert to verify the server.
                            oneOf:
                            - required:
                              - webPki
                            - required:
                              - secretClass
                            properties:
                              secretClass:
                                description: |-
                                  Name of the [SecretClass](https://docs.stackable.tech/home/nightly/secret-operator/secretclass) which will provide the CA certificate.
                                  Note that a SecretClass does not need to have a key but can also work with just a CA certificate,
                                  so if you got provided with a CA cert but don't have access to the key you can still use this method.
                                type: string
                              webPki:
                                description: |-
                                  Use TLS and the CA certificates trusted by the common web browsers to verify the server.
                                  This can be useful when you e.g. use public AWS S3 or other public available services.
                                type: object
                            type: object
                        required:
                        - caCert
                        type: object
                    type: object
                required:
                - verification
                type: object
            required:
            - host
            - port
            type: object
        required:
        - spec
        title: OpenLineageConnection
        type: object
    served: true
    storage: true
    subresources: {}
