[package]
name = "stackable-admission-controller"
version.workspace = true
authors.workspace = true
license.workspace = true
edition.workspace = true
repository.workspace = true

[dependencies]
axum.workspace = true
k8s-openapi.workspace = true
strum.workspace = true
tokio.workspace = true
