---
name: prek

on:
  pull_request:
  merge_group:

env:
  CARGO_TERM_COLOR: always
  RUST_TOOLCHAIN_VERSION: "nightly-2026-07-01"

permissions: {}

jobs:
  prek:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
        with:
          persist-credentials: false
          fetch-depth: 0
      - uses: stackabletech/actions/run-prek@a14cbd08d9e034e2361ea9205b32aff0491885db # v0.15.0
        with:
          rust: ${{ env.RUST_TOOLCHAIN_VERSION }}
          # rust-src is required for trybuild stderr output comparison to work
          # for our cases.
          # See: https://github.com/dtolnay/trybuild/issues/236#issuecomment-1620950759
          rust-components: rustfmt,clippy,rust-src
